### ISSUE TITLE
readFromSecureStore() usage question

### ISSUE THREAD

**Issue by getaaron** [matthewpalmer/Locksmith#100]
The README shows this example usage:

```swift
let account = TwitterAccount(username: "_matthewpalmer", password: "my_password")

// CreateableSecureStorable lets us create the account in the keychain
try account.createInSecureStore()

// ReadableSecureStorable lets us read the account from the keychain
let result = account.readFromSecureStore()
```

In this example `readFromSecureStore()` is called on an already existing instance of `TwitterAccount`. But if I'm launching my app from scratch and I want to *get* the `TwitterAccount`, how do I do that?

I think I'm looking for something on the class method like:

```swift
if let account = TwitterAccount.loadData(account: "_matthewpalmer") {
    // account is a TwitterAccount with a password
}
```

**Comment by matthewpalmer** [comment]
Definitely agree that this is an issue, and I don't really have any great answers sorry. Currently tracking possible solutions #92—would love to hear any thoughts in there :)

**Comment by getaaron** [comment]
Oh thanks… sorry for the dupe!
