### ISSUE TITLE
Updating branch 1.2.2 for swift 2.x

### ISSUE THREAD

**Issue by jomnius** [matthewpalmer/Locksmith#105]
This is more like a question: when maintaining one app, I found out it was using some old unknown version of Locksmith. I moved in under Cocoapods dependency management and upgraded to version 1.2.2, but then had to fix some compiler warnings. Would you be interested in a pull request of those fixes, maybe to create version 1.2.3? Currently (or even in near future) I have no time to upgrade to Locksmith 2.x APIs, but it's on todo list.

**Comment by matthewpalmer** [comment]
Hey

I'd love to see a PR for those fixes for 1.2.3—thanks!

If I were you I wouldn't rush to upgrade to 2.x... it's a pretty major API
change that I'm not convinced is well suited (as time goes on I feel like I
should probably add a note to the readme about this...)

**Comment by jomnius** [comment]
Ok, let's try: PR #107 is now available

**Comment by matthewpalmer** [comment]
Done. Thanks for the PR!
