### ISSUE TITLE
Can't get values back out of Locksmith

### ISSUE THREAD

**Issue by davejlong** [matthewpalmer/Locksmith#109]
I am building an app with the following workflow:

1. App loads a NavigationController
2. If user is not logged in
2.1. Root view controller is set to a LoginViewController
2.2. User enters credentials, credentials sent to server, token sent back to be stored in keychain with Locksmith
2.3. User is directed to Step 3
3. If user is logged in
3.1. TableViewController is shown within the NavigationController
3.2. Data is loaded from the server in the TableViewController

In the NavigationController's `viewWillAppear` method, I do a check for the token in Locksmith with my `User().isLoggedIn()` method. Then in my TableViewController's method to load data, I pull from `User().token` to make my request to the server. My user class looks like the following:

```swift
import Locksmith

let kAttrAccount = "Driver"
let kAttrService = "GoDriver"

class User {
  var token: String?
  
  init () {
    if let account = Locksmith.loadDataForUserAccount(kAttrAccount, inService: kAttrService) {
      if let token = account["token"] as? String {
        self.token = token
        print("Token: \(self.token)")
      }
    }
  }
  
  convenience init (token: String) {
    let _ = try? Locksmith.saveData(["token": token], forUserAccount: kAttrAccount, inService: kAttrService)
    self.init()
  }

  class func delete () {
    let _ = try? Locksmith.deleteDataForUserAccount(kAttrAccount, inService: kAttrService)
  }
  
  func isLoggedIn () -> Bool {
    if self.token == nil { return false }
    else { return true }
  }
}
```

From the NavigationController, `User().isLoggedIn()` returns true, but then in my TableViewController, `User().token` is nil. I'm not sure if there's an issue across threads or if there's some other issue causing my error.

**Comment by matthewpalmer** [comment]
Hmm interesting. Off the top of my head I'm not sure what the issue is, but I think we can resolve it. A couple of questions:

- for the line `let account = Locksmith.loadDataForUserAccount(kAttrAccount, inService: kAttrService)`, what is the value of `account`? Is it nil?
- what thread is `User(token: ...)` called on? (I don't think it's a threading issue but you never know)
- what's the error (if any) for `try? Locksmith.saveData(["token": token], forUserAccount: kAttrAccount, inService: kAttrService)`

Apologies if you've already checked all this stuff :smile:

**Comment by davejlong** [comment]
@matthewpalmer

> for the line let account = Locksmith.loadDataForUserAccount(kAttrAccount, inService: kAttrService), what is the value of account? Is it nil?

When called from my `NavigationController.viewWillAppear` method, the value is what I expected, a `Dictionary<String, Any>` object containing 1 element, my token. When called from my `TableViewController.viewWillAppear` method, the value is `nil` The TableViewController instance sits within the NavigationController.

> what thread is User(token: ...) called on? (I don't think it's a threading issue but you never know)

It's always from Thread 1 (com.apple.main-thread).

> what's the error (if any) for try? Locksmith.saveData(["token": token], forUserAccount: kAttrAccount, inService: kAttrService)

No error at all.

---

It seems like the token comes up empty only when I'm within nested view controllers (TableViewController within a NavigationController). Top level view controllers like the NavigationController and my LoginViewController can see the information just fine.

**Comment by davejlong** [comment]
Oddly enough, I just reimplemented my app using KeychainSwift and I get the same thing happening:

```swift
import KeychainSwift

let kAttrAccessGroup = "com.rudylimo.godriver"
let kAttrPrefix = "goDriver_"

class User {
  var token: String?
  
  let keychain: KeychainSwift = {
    let keychain = KeychainSwift(keyPrefix: kAttrPrefix)
    keychain.accessGroup = kAttrAccessGroup
    return keychain
  }()
  
  init () {
    self.token = keychain.get("token")
  }
  
  convenience init (token: String) {
    self.init()
    keychain.set(token, forKey: "token")
    self.token = keychain.get("token")
  }

  func delete () {
    User().keychain.clear()
  }
  
  func isLoggedIn () -> Bool {
    if self.token == nil { return false }
    else { return true }
  }
}
```

**Comment by matthewpalmer** [comment]
What happens if you try to load from the keychain in a method other than `viewWillAppear`?

**Comment by davejlong** [comment]
When I try to load from the keychain using a `UIRefreshControl` callback and it's the same issue.

**Comment by davejlong** [comment]
:tired_face: I just found a missing `!` point in the `if` statement checking on my login status which was logging me out causing the whole issue.
