### ISSUE TITLE
Locksmith.updateData( ) broke in 2.0.7?

### ISSUE THREAD

**Issue by frizzy75** [matthewpalmer/Locksmith#110]
My code was working fine until update to version 2.0.7. Now calling Locksmith.updateData( ) to save a new item fails with error errSecItemNotFound.

(Failure occurs at Locksmith.swift line 82)

Thanks

**Comment by lucasihlstrom** [comment]
I'm experiencing the same thing. It works on iOS 8.3 but fails on iOS 9.2.1.

**Comment by matthewpalmer** [comment]
Ah yep, this is a regression the tests missed. Will fix and put out a new version tonight. Thanks for letting me know 👍

**Comment by frizzy75** [comment]
Thank you very much!

**Comment by frizzy75** [comment]
@matthewpalmer Thank you for fixing so quickly.

**Comment by lucasihlstrom** [comment]
Yeah. Much appreciated :smile:!
