### ISSUE TITLE
Always get the same Error Code = 3

### ISSUE THREAD

**Issue by nicopuri** [matthewpalmer/Locksmith#111]
Hi,

I always get the same error:

```
Locksmith.LocksmithError Code=3 "(null)"
```

I'm trying to save an String but it failed. I don't know what the error could it be. Can you help me? It'd helpful if I can see the `OSStatus`.

**Comment by matthewpalmer** [comment]
Hey @nicopuri 

Is this a new error (i.e. code was working before and has stopped)? What code are you using that causes the error? 

Thanks
