### ISSUE TITLE
Error code 7 after upgrade to 2.0.7

### ISSUE THREAD

**Issue by focusedonfit** [matthewpalmer/Locksmith#112]
I recently upgraded from 2.0.2 to 2.0.7. I'm now receiving an error when attempting to save to the key chain. Here is my code for updateData:
    try Locksmith.updateData(["access_token":accessToken,"refresh_token": refreshToken,"expires_in": "\(expiresIn)","creation_date": "\(stringDate)" ], forUserAccount: "\(username)", inService: "FocusedOnTraining")

here is the error I receive:
couldn't save json Error Domain=Locksmith.LocksmithError Code=7 "(null)"
Error Domain=Locksmith.LocksmithError Code=7 "(null)"

thank you for the help.

**Comment by matthewpalmer** [comment]
Hi,
Do you get an error if using version 2.0.8? 2.0.8 fixed an issue when
updating

**Comment by focusedonfit** [comment]
Haven't tried that. I'm installing via cocoa pods, 2.0.7 is the latest there.

**Comment by focusedonfit** [comment]
just cleared pod cache and got 2.0.8. Will test

**Comment by focusedonfit** [comment]
Yes 2.0.8 works. Thank you!
