### ISSUE TITLE
SO Question: fatal error: unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by JamesGDEv** [matthewpalmer/Locksmith#113]
Sorry, was not sure how to message you so I thought I would ask on here if you can help me on stackoverflow?: http://stackoverflow.com/questions/35564497/swift-locksmith-fatal-error-unexpectedly-found-nil-while-unwrapping-an-optiona

**Comment by matthewpalmer** [comment]
Looks like @getaaron hit the nail on the head on stackoverflow. Closing this issue, let me know if you have any more questions :+1:
