### ISSUE TITLE
Under swift, do I need to import the security framework manually to use the keychain?

### ISSUE THREAD

**Issue by Johannes-HAWHH** [matthewpalmer/Locksmith#115]
Hello there,
I'm using the KeychainWrapper in my project and everything works fine but now I wonder about the need for the security framework which I didn't import manually. Is this something I still need to do in swift? I can Cmd+click those kSec keys in the wrapper and it sends me to the security framework - does this mean it's "built in" into swift now or something like that?

If I do need that framework why does it work right now "without" it? Are my strings saved but not encrypted or something like that?

Btw: I asked that on SO as well but the answers weren't completely satisfying thats why I ask here now.

Thanks a lot in advance

**Comment by matthewpalmer** [comment]
Hmm it's a good question, and I'm not 100% sure what the answer is. Let me know if you find a good answer!

Just opened up a new iOS project and something from the `Security` framework like `SecItemCopyMatching` is available straight away, but if you try another iOS SDK framework like `Accounts` with `ACAccount` you need to add `import Accounts` to the Swift file. My best guess is that the Security framework is automatically imported, but I have no documentation to back that up.

**Comment by matthewpalmer** [comment]
Closing this, but feel free to reopen if more discussion is needed
