### ISSUE TITLE
Compilation issue when using xcode7.3

### ISSUE THREAD

**Issue by eniyavans** [matthewpalmer/Locksmith#116]
Got the following compilation issue when using xcode7.3

Pods/Locksmith/Pod/Classes/LocksmithRequest.swift:121:42: redundant conformance
 of 'LocksmithRequest' to protocol 'CustomDebugStringConvertible'

public class LocksmithRequest: NSObject, CustomDebugStringConvertible {
}

**Comment by matthewpalmer** [comment]
Thanks for letting me know. Right now I don't have enough hard drive space on my computer to update to Xcode 7.3 to fix this (128gb is too small!), but would love to accept a PR and make a release

**Comment by matthewpalmer** [comment]
I just built and ran the example project with Xcode 7.3 (7D175) and it didn't give me any issues. What am I missing?

Thanks

**Comment by matthewpalmer** [comment]
Oh wait which version of Locksmith are you using?

**Comment by eniyavans** [comment]
I was using v2.0 hence i was getting this issue. In v2.0.8 not getting this issue.You can close this issue. Thanks for your support.

**Comment by netoleal** [comment]
Guys, actually i'm getting this same error. I'v downloaded the source from the master branch. Any ideas? Thanks!

**Comment by anthonydiep** [comment]
I encountered the same error and was wondering what would be the impact of changing conformance from
`NSObject, CustomDebugStringConvertible`
to
`CustomDebugStringConvertible`

Would that be a possible fix or do you think it might cause problems further down the road ?
