### ISSUE TITLE
Error Code: 34018 - Generated when attempting to load object from keychain after re-installation (first run only)

### ISSUE THREAD

**Issue by NitWitStudios** [matthewpalmer/Locksmith#12]
Hello!

Love this library. Having one issue though that is kind of major for me.
In my app, I offer "one free" item. In order to prevent users from just deleting and re-installing the app to unlock other items, I am storing that item identifier in the keychain (kSecAttrService). I need this to persist across app removal. (and no, my app does not require user authentication so I don't track users which would allow me to remotely managed the unlocked item. I need it all on the device itself).

Locksmith works great, however I discovered that an error is generated on the first run when I uninstall and re-install the app. However, quitting and re-running the app I am able to load the object from the keychain just fine (without deleting the app).
**So it seems the object is in fact persisting across deletions, but just has a problem on the first run of a re-installation.**
Any ideas? This is the last bug I need fixed before submitting to the app store, so I am anxiously awaiting your answer!

Here is the error:

    Error Domain=com.locksmith.error Code=-34018 "The operation couldn’t be completed. (com.locksmith.error error -34018.)" UserInfo=0x174e39360 {message=Undocumented error with code -34018.}

Thanks!
James

**Comment by NitWitStudios** [comment]
Ok - found a hotfix for my case.
My code was originally like this when checking for a saved item:

     let (dictionary, error) = Locksmith.loadDataInService(KeychainServiceType, forUserAccount: KeychainUserAccount)

        if (error != nil)
        {
            return false
        }
        
        if let savedProductIdentifier = dictionary![KeychainFreeProductKey] as? String
        {
             ...check object key for item identification....
             return true
        }

By removing the 'if (error !=nil)' segment, I was able to load the object just fine. Not sure why an error is being returned even though the keychain object is loaded just fine. May be worth looking into, but for now can just remove the error check.

**Comment by matthewpalmer** [comment]
I'm glad you were able to get it working. I will definitely look into it—it's a really strange issue because the error code isn't mentioned in Apple's documentation at all. Thanks for letting me know :)

 I'm wondering if it's some kind of Keychain initialisation bug. What happens if you perform a dummy keychain request before the proper one? (this would only need to be done on first launch)

**Comment by kristalpollack** [comment]
I just hit this issue as well and it looks like Apple is now able to reproduce it and is working on a fix:

https://forums.developer.apple.com/thread/4743#14441
