### ISSUE TITLE
How is do try catch errorhandling done with Locksmith?

### ISSUE THREAD

**Issue by rlam3** [matthewpalmer/Locksmith#125]
How should do try catch error handling done with Locksmith? Please provide example. Or is there a better solution to this? 
Thanks! 
```
do{
    try Locksmith.saveData(userCredentialDict, forUserAccount: authCred["username"] as! String)
}catch is ErrorType{
    //print(ErrorType)
    
}
```

**Comment by piotr-dudek** [comment]
@rlam3 If you want to catch specific Locksmith error you may try something like this: 
```
do {
    try Locksmith.saveData(userCredentialDict, forUserAccount: authCred["username"] as! String)
} catch LocksmithError.Duplicate {
    // do something in reponse to Duplicate error
} catch {
    // do something in reponse to any other error
    print(error)
}
```
Here you can find Locksmith error types: [LocksmithError.swift](https://github.com/matthewpalmer/Locksmith/blob/master/Source/LocksmithError.swift)

**Comment by matthewpalmer** [comment]
Thanks Piotr! 👍
