### ISSUE TITLE
Swift 3 Support

### ISSUE THREAD

**Issue by davbeck** [matthewpalmer/Locksmith#129]
In order for an app to migrate to Swift 3, every one of it's libraries needs to use it as well. I talked to some of the engineers at WWDC, and they were very adamant that Swift 2.3 was a temporary stop gap to give people more time to migrate to 3, but not a longterm solution. It's my opinion that Swift frameworks should maintain branches for each major version of Swift (i.e. swift-2.2, swift-2.3 and swift-3.0) so that apps can target the version they are using specifically.

I've already submitted a [pull request](https://github.com/matthewpalmer/Locksmith/pull/128) for Swift 2.3, but I recommend you create a swift-2.3 branch and close that request so that I can create a new one directed at that branch.

I have [a branch](https://github.com/davbeck/Locksmith/tree/swift-3.0) with the library converted to Swift 3 building, but there is a test that is failing. I'm not familiar enough with the framework to understand why it's failing though. Additionally, I haven't adopted any of the new style guidelines introduce with Swift 3. Perhaps we could create a swift-3.0 branch, merge that into it, and go from there to get a fully working and migrated version for 3.0.

**Comment by testzugang** [comment]
Here is the current patch needed for Swift 3 support.
[Locksmith.txt](https://github.com/matthewpalmer/Locksmith/files/346513/Locksmith.txt)

**Comment by matthewpalmer** [comment]
Thanks very much! I should have time to look into this on the weekend 😄

**Comment by AndrewSB** [comment]
@matthewpalmer would love to see this implemented! This library and Moya are the only two that I'm still waiting on to upgrade to Swift 3

**Comment by fedetrim** [comment]
Xcode 8 GM is scheduled to be released tomorrow, and we will be able to start submitting apps to the App Store compiled with Swift 3. 
I want to support Swift 3 in my app but I can't because Locksmith is stuck in beta 4.

@matthewpalmer when do you think Locksmith will support Swift 3?

**Comment by AndrewSB** [comment]
@fedetrim where did you read that GM is to be released tomorrow? Or are you
inferring it will be based on the keynote happening tomorrow?

**Comment by fedetrim** [comment]
@AndrewSB Xcode 8 GM has just been released, following today's keynote.
https://developer.apple.com/news/?id=09072016a

**Comment by AndrewSB** [comment]
awesome 😄

**Comment by emreavsar** [comment]
waiting for swift 3 support..

**Comment by mschonvogel** [comment]
@matthewpalmer when do you think Locksmith will support Swift 3?

**Comment by matthewpalmer** [comment]
See https://github.com/matthewpalmer/Locksmith/pull/140

**Comment by matthewpalmer** [comment]
Merged in #143
