### ISSUE TITLE
Fix library for proper Compiler-Level Optimization Setting (Release Build Crash Fix)

### ISSUE THREAD

**Issue by NitWitStudios** [matthewpalmer/Locksmith#13]
I recently submitted my app to the store not realizing this library requires the optimization level of the compiler to be set to 'None' or it crashes on launch for release build. As a result, it was rejected by Apple due to crashing on start up.
I have since changed it to 'None' and now the app runs fine on release build, but reading Apple's documentation it states specifically the following for *Compiler-Level Optimization* of type *None*:

     None - The compiler does not attempt to optimize code. Use this option during development when you are focused on solving logic errors and need a fast compile time. Do not use this option for shipping your executable.

The **Do not use this option for shipping your executable** concerns me a bit for releasing a non-optimized build to the App Store.
Is there any possibility of fixing this library to not require this setting?

**Comment by NitWitStudios** [comment]
From my brief research, I think the issue may be stemming from your use of Unmanaged<AnyObject>? and UnsafeMutablePointer<Unmanaged<AnyObject>?> in the library.

Here is some related issues I found that discussed the same problem:
http://stackoverflow.com/questions/9431583/crash-at-any-optimization-level-other-than-o0-in-ios
http://stackoverflow.com/questions/24215757/using-unmanagedanyobject-as-key-in-nsmutabledictionary

**Comment by matthewpalmer** [comment]
Oh man I’m really sorry that this caused your app to be rejected :(. It's the worst when 3rd party libraries cause problems in your app.

The problem is that the Keychain Services API requires the use of an UnsafeMutablePointer to an Unmanaged AnyObject, i.e.

```swift
func SecItemCopyMatching(query: CFDictionary!, result: UnsafeMutablePointer<Unmanaged<AnyObject>?>) -> OSStatus
```

Unfortunately, I can't think of any way of getting around this requirement.

If possible, I recommend @soffes's SSKeychain. It's really stable and written in Objective-C, so it shouldn't have any of these crazy issues. Hopefully Apple fixes this bug ASAP.

Sorry again,
Matt.

**Comment by beltex** [comment]
Hi @NitWitStudios & @matthewpalmer,

I can't seem to reproduce the crash. Do you have a stack trace you could share?

Pinpointing these crashes and collecting them is what the [swift-compiler-crashes](https://github.com/practicalswift/swift-compiler-crashes) project does, so finding and documenting everyone of these helps.

**Comment by matthewpalmer** [comment]
I think Issue #6 Is the original incarnation of this crash. That thread has a lot more information and ways to force the crash.
If you're still unable to reproduce the crash, let me know and I'll look into it.

Cheers,
Matt.

**Comment by beltex** [comment]
Darn, I should have search for it, my mistake! Thanks Matt! :)

**Comment by moshegutman** [comment]
I was able to fix a similar issue with help from this link:
http://stackoverflow.com/questions/24145838/querying-ios-keychain-using-swift

```
var returnedData: AnyObject?
var results = withUnsafeMutablePointer(&returnedData) { SecItemCopyMatching(query, UnsafeMutablePointer($0)) }
```

**Comment by Arcrammer** [comment]
Would the compiler crash if you use ```withUnsafeMutablePointer()```?

**Comment by moshegutman** [comment]
My project is compiling without issues. It is a valid Swift function: 
http://swiftdoc.org/func/withUnsafeMutablePointer/

**Comment by olvidalo** [comment]
I replaced all the unmanaged objects with the withUnsafeMutablePointer function which seemed to have resolved at least my issue where I would get a duplicate item-error when trying to save data in the release configuration with something other than -Onone.

**Comment by matthewpalmer** [comment]
Thanks for all of the help everyone, and cheers to @olvidalo for the fix :)

**Comment by NitWitStudios** [comment]
Awesome! Thumbs up to everyone who got involved in this issue! :+1:
