### ISSUE TITLE
Support for Xcode 8 with Swift 2.3

### ISSUE THREAD

**Issue by DenHeadless** [matthewpalmer/Locksmith#143]
@matthewpalmer Hey!
It seems like release for Swift 2.3 will also be needed, cause iOS 10 SDK seems to break something in Locksmith.

For example following test succeeds on Xcode 7.3.1 with Swift 2.2 and iOS 9 SDK, and fails on Xcode 8 with Swift 2.3 and iOS 10 SDK

```swift
class LocksmithTestCase : XCTestCase {
    func testItemIsPersisted() {
        _ = try? Locksmith.saveData(["foo":"bar"], forUserAccount: "Account")
        let bar = Locksmith.loadDataForUserAccount("Account")
        XCTAssertEqual(bar?["foo"] as? String,"bar")
    }
}
```

I tried to debug the reason and it seems that when reading from Keychain on this line:
https://github.com/matthewpalmer/Locksmith/blob/master/Source/Locksmith.swift#L78

I receive status code -25300.

I'm not sure how to properly fix this and how it's related to #142.

I would be happy to provide more debug information, if you need it.

**Comment by DenHeadless** [comment]
Update: turning Keychain Sharing on app target fixes the issue. However i don't have multiple apps, that wan't to share keychain items with, so this probably should not be a default. Maybe iOS 10 SDK changes some behavior, and accessGroup parameter gets into default options, even though it's not set?

**Comment by fedetrim** [comment]
@DenHeadless I believe the issue only happens in the simulator

**Comment by DenHeadless** [comment]
Confirmed. Seems like turning on Keychain Sharing is the only way to fix tests) What's funny is that tests work even if there are 0 keychain groups in capabilities pane.

Anyway, thank you for quick response! Closing.
