### ISSUE TITLE
52+ errors... XCode 8

### ISSUE THREAD

**Issue by mdridley** [matthewpalmer/Locksmith#145]
Finally updating a new project to Swift 3.0... but having trouble with LockSmith:

I tried downloading the 3.0 branch code and replacing the files... but still seems like a lot of broken stuff. I feel like I must be doing something wrong on my end. Or did some stuff change last minute that is breaking the last 3.0 changes?

![image](https://cloud.githubusercontent.com/assets/1685242/18519256/e08bf208-7a68-11e6-9cc8-7ee3516f6dd1.png)

**Comment by thatjuan** [comment]
@mdridley Are you using cocoapods? Just wondering. I'm having a heck of a time upgrading all my project dependencies, Locksmith being one of them.

**Comment by mdridley** [comment]
I am.

**Comment by rlam3** [comment]
+1

**Comment by matthewpalmer** [comment]
Hmm, could be wrong but I don't think you're using the latest from `swift-3.0`. The code you posted isn't updated for Swift 3.0, and doesn't exist—it's now

```
public extension SecureStorable where Self : InternetPasswordSecureStorable {
    fileprivate var internetPasswordBaseStoragePropertyDictionary: [String: Any] {
        var dictionary = [String: Any]()
        
        // add in whatever turns out to be required...
        dictionary[String(kSecAttrServer)] = server
        dictionary[String(kSecAttrPort)] = port
        dictionary[String(kSecAttrProtocol)] = internetProtocol.rawValue
        dictionary[String(kSecAttrAuthenticationType)] = authenticationType.rawValue
        dictionary[String(kSecAttrSecurityDomain)] = securityDomain
        dictionary[String(kSecAttrPath)] = path
        dictionary[String(kSecClass)] = LocksmithSecurityClass.internetPassword.rawValue
        
        let toMergeWith = [
            accountSecureStoragePropertyDictionary,
            describableSecureStoragePropertyDictionary,
            commentableSecureStoragePropertyDictionary,
            creatorDesignatableSecureStoragePropertyDictionary,
            typeDesignatableSecureStoragePropertyDictionary,
            isInvisibleSecureStoragePropertyDictionary,
            isNegativeSecureStoragePropertyDictionary
        ]
```

**Comment by ehabsaifan** [comment]
I have the same issue... Just like you

**Comment by matthewpalmer** [comment]
Can you please provide more info?

**Comment by ehabsaifan** [comment]
This my Podfile,  and I am using cocoPods 1.1.0
`# Uncomment this line to define a global platform for your project
# platform :ios, ‘9.0’

use_frameworks!

target ‘Dropspot’ do
    pod 'MBProgressHUD'
    pod 'SwiftyJSON'
    pod 'Alamofire', '~> 4.0'
    pod 'Stripe'
    pod 'Bolts'
    pod 'FBSDKCoreKit'
    pod 'FBSDKShareKit'
    pod 'FBSDKLoginKit'
    pod 'AWSCore'
    pod 'AWSS3'
    pod 'Locksmith', 
    :git => 'https://github.com/davbeck/Locksmith.git',
    :branch => 'swift-3.0'
    pod 'Google/Analytics'
    pod 'SwiftQRCode'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
`

I have the same issues as "mdridley"

**Comment by matthewpalmer** [comment]
You are using `https://github.com/davbeck/Locksmith.git` not this repo

**Comment by ehabsaifan** [comment]
I am new to iOS I appreiate your help! Could you please explain more

**Comment by matthewpalmer** [comment]
Replace `https://github.com/davbeck/Locksmith.git` with `https://github.com/matthewpalmer/Locksmith.git` in your podfile and let me know how it goes 👍

**Comment by ehabsaifan** [comment]
Thank You I guess the problem resolved :) 👍

**Comment by mdridley** [comment]
I downloaded the 3.0 branch, and replaced the files in: Pods/Locksmith/
Is there a better place to do that or something else I should do to make sure it uses the new files?

**Comment by mdridley** [comment]
Updating podfile as suggested worked. Thank you!!!

**Comment by siavashalipour** [comment]
@matthewpalmer Could you please add a release version as well? I can't use this branch as an dependency in podspec

**Comment by matthewpalmer** [comment]
@siavashalipour done. Closing this issue now 👍
