### ISSUE TITLE
Create CocoaPod for this library

### ISSUE THREAD

**Issue by NitWitStudios** [matthewpalmer/Locksmith#15]
Was wondering if you plan on/can make a cocoa pod for this library? Would make it easier to update. :-)

**Comment by matthewpalmer** [comment]
Yeah I think I will. Last time I tried it didn’t work out, but I’ll have another go over the next few days.

Cheers for the suggestion :)=

**Comment by matthewpalmer** [comment]
Do you know of any existing Swift projects that are in Cocoapods? Just looking for a few examples of how they have everything structured.

**Comment by getaaron** [comment]
@matthewpalmer Here's a Swift + CocoaPods project I worked on with @ArtSabintsev: [Siren](https://github.com/ArtSabintsev/Siren). Let us know if you have any questions; it was a bit different than we were expecting.

**Comment by matthewpalmer** [comment]
Added in cf322dc. Still a little bit of cleanup to do, which will be fixed in version 1.1.1.

Thanks guys :)
