### ISSUE TITLE
Swift 4 support

### ISSUE THREAD

**Issue by kubajakowski** [matthewpalmer/Locksmith#177]
Is it planned?

**Comment by joergsimon** [comment]
would be interested in that too

**Comment by SellJamHere** [comment]
👍

**Comment by clayellis** [comment]
@matthewpalmer Please let us know if you're planning on upgrading to Swift 4 or if we need to abandon Locksmith. Your community is depending on you 😉

**Comment by aehlke** [comment]
There are forks, FYI.

**Comment by clayellis** [comment]
@aehlke Fair enough.

**Comment by rlam3** [comment]
@matthewpalmer If you'd like the community to help you with keeping the updates for this packag, please let us know. As we always would love to offer a extra pair of hands. We'd love to help you. Thanks!

**Comment by matthewpalmer** [comment]
Fixed in #179—my apologies for the delay 👍
