### ISSUE TITLE
Redundant conformance to SecureStorableResultType?

### ISSUE THREAD

**Issue by abhishekbanthia** [matthewpalmer/Locksmith#178]
I'm seeing the following warning in Swift 3.0, Xcode 9:

<img width="269" alt="screen shot 2017-09-18 at 1 38 25 pm" src="https://user-images.githubusercontent.com/8280282/30558411-de336de8-9c76-11e7-835a-e210e8929d55.png">

**Comment by initFabian** [comment]
Hey @abhishekbanthia, #179 was merged that fixed this issue.

**Comment by n0shake** [comment]
Great. Closing.
