### ISSUE TITLE
App crashing when calling 'loadDataForUserAccount'

### ISSUE THREAD

**Issue by RPiyush** [matthewpalmer/Locksmith#182]
I am using swift 3 and Locksmith version 4.

when I call 
**Locksmith.loadDataForUserAccount(userAccount: "test")** 
my application crashes her, any suggestion for this?

**Comment by crpr** [comment]
This is happening to me to with this exception -[NSDictionary initWithObjects:forKeys:]: count of objects (0) differs from count of keys (1)'
