### ISSUE TITLE
Only 1 item returned in loadDataForUserAccount

### ISSUE THREAD

**Issue by roxberry** [matthewpalmer/Locksmith#19]
I'm trying to add multiple entries to the dictionary - assuming it was 1 account to many key/value pairs:

```swift
let error = Locksmith.saveData(["userid": client.currentUser.userId], forUserAccount: "user1", inService: "demoService")
let error = Locksmith.saveData(["token": client.currentUser.mobileServiceAuthenticationToken], forUserAccount: "user1", inService: "demoService")
```

I call the loadDataForUserAccount and only get 1 key value pair for key "userid" in the returned dictionary:

```swift
let (dictionary, error) = Locksmith.loadDataForUserAccount("user1", inService: "demoService")
```
Is this by design (I'm new to Swift)?  Peeked at your code and figure the NSMutableDictionary allowed for multiple entries, but maybe I missed something.

**Comment by matthewpalmer** [comment]
The calls to Locksmith.saveData won’t mutate what’s already saved in the keychain.

What you could do is to call Locksmith.saveData([“userid": client.currentUser.userId, “token”: client…token], forUserAccount: …). Then when you load the data back it will have both fields.

Does that fit your use case?=

**Comment by roxberry** [comment]
Yeah - that works a little better with the JSON config that we pass down (just slam it in).  Thanks.
