### ISSUE TITLE
Cocoapod Compile Error: error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: unknown option character `X' in: -Xlinker

### ISSUE THREAD

**Issue by NitWitStudios** [matthewpalmer/Locksmith#22]
Tried to switch to cocoapod for including this library in my project. Getting this error at compile time:

     error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: unknown option character `X' in: -Xlinker
     Usage: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -static [-] file [...] [-filelist listfile[,dirname]] [-arch_only arch] [-sacLT] [-no_warning_for_no_symbols]
     Usage: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -dynamic [-] file [...] [-filelist listfile[,dirname]] [-arch_only arch] [-o output] [-install_name name] [-compatibility_version #] [-current_version #] [-seg1addr 0x#] [-segs_read_only_addr 0x#] [-segs_read_write_addr 0x#] [-seg_addr_table <filename>] [-seg_addr_table_filename <file_system_path>] [-all_load] [-noall_load]

**Comment by matthewpalmer** [comment]
Are you definitely using the latest version of Cocapods? (http://matthewpalmer.net/blog/2015/01/25/publish-swift-cocoapods/ <http://matthewpalmer.net/blog/2015/01/25/publish-swift-cocoapods/>)=

**Comment by NitWitStudios** [comment]
Ok followed those steps and now I get this error:

     <unknown>:0: error: could not build Objective-C module 'Locksmith'

**Comment by matthewpalmer** [comment]
Hmm weird. If you haven't already, try the following

- clean all derived data and re-build
- Try these steps: http://stackoverflow.com/questions/26834293/swift-could-not-build-objective-c-module-alamofire
- Try this: http://stackoverflow.com/questions/26097747/error-underlying-objective-c-module-insert-module-name-here-not-found

**Comment by matthewpalmer** [comment]
Closing. Feel free to reopen if there's still no fix.
