### ISSUE TITLE
Adding Locksmith to pod file causes error

### ISSUE THREAD

**Issue by rogerkerse** [matthewpalmer/Locksmith#26]
Since I added it to pod file and just install it and do nothing else, I already get an error

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: unknown option character `X' in: -Xlinker

**Comment by matthewpalmer** [comment]
Make sure you’re using the prerelease version of Cocoapods. I had two versions installed side-by-side and I got that error when it accidentally used the older version.
