### ISSUE TITLE
xCode Beta 3 compiler error

### ISSUE THREAD

**Issue by steilerDev** [matthewpalmer/Locksmith#27]
After adding Locksmith to my Swift project I get the following compiler error: 

[...]/Pods/Locksmith/Pod/Classes/Locksmith.swift:12:100: 'AnyObject?' is not convertible to 'String'; did you mean to use 'as!' to force downcast?

I am following xCode's suggestion, but I am not sure if this changes the behaviour of your application.

**Comment by mcgraw** [comment]
+1 Needs Swift 1.2 support

**Comment by matthewpalmer** [comment]
#25 adds Swift 1.2 support. I'll merge that fix in once 1.2 is finalised and released.

**Comment by mcgraw** [comment]
Thanks @matthewpalmer!

**Comment by firedog7881** [comment]
Now that 1.2 is finalised and released can we get the merge? Thank you for your great work.

**Comment by matthewpalmer** [comment]
Just pushed to cocoapods. Let me know if there are any issues :)
