### ISSUE TITLE
I can't save multiple dictionaries for the same user account?

### ISSUE THREAD

**Issue by rlam3** [matthewpalmer/Locksmith#28]
I'm a bit confused here. I can't save multiple dictionaries for the same account for the same service? 

	var errors: [NSError?] = []

	errors.append(Locksmith.saveData(jwt_token_dict, forUserAccount: user_account, inService:service))
	errors.append(Locksmith.saveData(user_name_dict, forUserAccount: user_account, inService: service))
	errors.append(Locksmith.saveData(password_dict, forUserAccount: user_account, inService: service))

jwt_token_dict saves but the user_name_dict and password_dict cannot be saved because it is complaining about "The operation couldn’t be completed" and {message=The item already exists.} ?

Or am I doing something wrong?

**Comment by matthewpalmer** [comment]
The userAccount and service uniquely identify the dictionary being saved. You can merge those dictionaries together and save/load them in one call, or save them under different accounts/services. If you want to update currently stored data, you can use the `updateData` method (this is essentially performing a delete then a save operation).
