### ISSUE TITLE
Crash on -34018 (undocumented errSecMissingEntitlement)

### ISSUE THREAD

**Issue by hborders** [matthewpalmer/Locksmith#31]
There is a [old, rare bug](https://devforums.apple.com/thread/246122?tstart=0) in the iOS keychain that Apple has no fix for and can't reliably reproduce. The suggested workaround is to restart the app. Crashing when we see this error seems like a reasonable default.

Reposting a relevant portion of the linked devforums thread below:

> Error -34018 is not publicly documented but it translates to errSecMissingEntitlement.  In most cases this means that your app has been signed with the wrong entitlements.  However, that's unlikely to be the case here because your app works the vast majority of the time.
> 
> There have been various reports of this cropping up sporadically over the years.  If you search DevForums for "34018" you'll see it mentioned a bunch of times, not all of which are related to the way the app was built.  Alas, I've never uncovered any other common causes for this error.
> 
> Have you ever managed to reproduce this an a device which you control?  Does the problem go away when you restart that device?
>
> Share and Enjoy
> <p>--</p>
> Quinn "The Eskimo!" &lt;eskimo1@apple.com&gt;
> Apple Developer Relations, Developer Technical Support, Core OS/Hardware

**Comment by matthewpalmer** [comment]
Thanks for letting me know about that bug! I'm sure it's going to help people who come searching in the future.

I'm hesitant to cause a crash if we get into an unreliable state. I imagine that could be frustrating to debug for users of this library. The alternative would be to log the error and return `nil` where appropriate, which I think we might be doing already (let me know if this is not the case and we can update the library to do that).

Sorry for taking so long to comment on this. Feel free to reopen and leave a comment if this doesn't handle your query :)
