### ISSUE TITLE
Why is userAccount required?

### ISSUE THREAD

**Issue by allaire** [matthewpalmer/Locksmith#32]
Why is userAccount a central piece in Locksmith API? I almost see no trace of userAccount in https://github.com/kishikawakatsumi/KeychainAccess and my app only need to store an API token.

Thanks for your time

**Comment by matthewpalmer** [comment]
userAccount is used as the equivalent to kSecAttrAccount in the regular keychain. Without looking too deeply at the code, my guess is the string they are using in the subscript is their equivalent of the user account in Locksmith.

e.g. In `keychain.set("01234567-89ab-cdef-0123-456789abcdef", key: "kishikawakatsumi")`, `"kishikawakatsumi"` would be the userAccount.

Sorry for taking so long to get back to you! Hopefully this helps :)
