### ISSUE TITLE
"Cannot Load Underlying Module" when using Cocoapods

### ISSUE THREAD

**Issue by seenickcode** [matthewpalmer/Locksmith#35]
Hello, I'm using cocoapods to install but when I attempt to ``import Locksmith`` I get an error:  ``Cannot load underlying module for Locksmith``

This is my Podfile

````
platform :ios, '8.0'

use_frameworks!

pod 'Locksmith'
````
Thanks

**Comment by matthewpalmer** [comment]
Hmm interesting. Are you able to reproduce this on a new/clean project?

Random things that might help, but you've probably already tried:

- re-running `pod install` on the directory
- cleaning derived data
- cleaning module cache
- quitting xcode, reopening the .xcworkspace

Let me know how that goes :)

**Comment by matthewpalmer** [comment]
Closing. Reopen if the issue persists :)

**Comment by seenickcode** [comment]
Will do @matthewpalmer thanks for the support.
