### ISSUE TITLE
Swift 2 Support

### ISSUE THREAD

**Issue by rrbrambley** [matthewpalmer/Locksmith#37]
Looks like the Xcode-provided Swift upgrade tool handles everything except some casting that's needed in line 12 of Locksmith.swift:

```swift
public let LocksmithDefaultService = 
    NSBundle.mainBundle().infoDictionary![kCFBundleIdentifierKey as String] as? String ?? "com.locksmith.defaultService"
```

**Comment by matthewpalmer** [comment]
Awesome, thanks! Will make these changes once Xcode 7/Swift 2 settles in a bit :)

**Comment by prefect42** [comment]
Would be great if you could merge in the Pull Request by SirWellington on a swift 2.0 branch.
Another branch is needed anyway.
You could then take your time on doing the other optimizations you were talking about in the coming weeks, but early adopters like me could quickly use this fine piece of work again.

**Comment by matthewpalmer** [comment]
Done. Cheers for the suggestion 👍. Let me know if there’s anything else that needs to be done.

**Comment by matthewpalmer** [comment]
Added some more changes for Swift 2 on the `2.0` branch, most notably with support for the new error handling style. I still need to update the README. Closing this issue, but feel free to reopen if necessary.

**Comment by prefect42** [comment]
Thanks
