### ISSUE TITLE
NSDictionary vs Dictionary

### ISSUE THREAD

**Issue by kayvink** [matthewpalmer/Locksmith#39]
Is there a reason why `Locksmith.loadDataForUserAccount()` returns a `NSDictionary?` instead of a `Dictionary<String,AnyObject>?` ?

**Comment by matthewpalmer** [comment]
Nothing that I can think of off the top of my head. Feel free to branch off the 2.0 branch and submit a PR :)

**Comment by matthewpalmer** [comment]
Closing, but feel free to re-open if you think this deserves more attention/is in the midst of a pull request 👍

**Comment by kayvink** [comment]
Had a look at this today, `Dictionary<String,AnyObject>` also works for storing `Int`s and `Double`s. I'm not currently on Swift 2, have to work with the stable release. Shall I put a PR in for the current version?

**Comment by kayvink** [comment]
https://github.com/matthewpalmer/Locksmith/pull/48

**Comment by kayvink** [comment]
https://github.com/matthewpalmer/Locksmith/pull/49 --> Updated PR
