### ISSUE TITLE
'()' is not convertible to 'StringLiteralConvertible' Locksmith on saveData

### ISSUE THREAD

**Issue by Lvkz** [matthewpalmer/Locksmith#40]
I'm updating my app to swift 2.0, and updated de code of Locksmith for swift 2.0, but I can't get rid off this:
<code>'()' is not convertible to 'StringLiteralConvertible' Locksmith</code>

And the line giving this error is this: 
<code>
try user_error = Locksmith.saveData(["username" : txtuserName.text, "password" : txtPassword.text], forUserAccount: "AppAccount")
</code>

As you can see, I'm trying to save a dictionary with the username and password into the keychain. Don't know if this is a bug or an issue, but it the previous version it worked and I can't go back to the previous version of Swift.

**Comment by matthewpalmer** [comment]
Hmm interesting. What are the types of txtuserName.text and txtPassword.text?
If they are optional strings I don't think it'll work.

**Comment by Lvkz** [comment]
They are UITextField, but there are not optional: 
<code>@IBOutlet weak var txtuserName: UITextField!</code>
<code>@IBOutlet weak var txtPassword: UITextField!</code>

**Comment by matthewpalmer** [comment]
I think the 'text' property of UITextField might be optional.

**Comment by matthewpalmer** [comment]
Sorry, email client truncated your comment. Will reread and comment again...

**Comment by matthewpalmer** [comment]
Awesome. Glad it worked for you! Feel free to reopen if you have any more issues :)

**Comment by getaaron** [comment]
@Lvkz You might want to open a radar for a more helpful error message

**Comment by Lvkz** [comment]
Mmm.... Interesting, how does that work? (Pardon my ignorance).
