### ISSUE TITLE
Undocumented error with code -25243

### ISSUE THREAD

**Issue by tosbaha** [matthewpalmer/Locksmith#41]
I am trying to use Locksmith to share sensitive data with my application and extension. I turned on Keychain Sharing on both App and widget with same identifier. In my App.entitlements and Widget.entitlements I have following set

``` $(AppIdentifierPrefix)com.domain.Appname ```

I changed convenient class methods as below

```swift
    public class func saveData(data: Dictionary<String, String>, forUserAccount userAccount: String, inService service: String = LocksmithDefaultService) -> NSError? {
        let saveRequest = LocksmithRequest(userAccount: userAccount, requestType: .Create, data: data, service: service)
        saveRequest.group = "com.domain.Appname"
        let (dictionary, error) = Locksmith.performRequest(saveRequest)
        return error
    }
    
    public class func loadDataForUserAccount(userAccount: String, inService service: String = LocksmithDefaultService) -> (NSDictionary?, NSError?) {
        let readRequest = LocksmithRequest(userAccount: userAccount, service: service)
        readRequest.group = "com.domain.Appname"
        return Locksmith.performRequest(readRequest)
    }
```

When I try to save the data I got error message ```{message=Undocumented error with code -25243.})```

**Comment by tosbaha** [comment]
I have found out that I had to set **TeamID** as group name so it must be ```TeamID.com.domain.Appname``` I also found out that if both targets have single keychain group, you don't need to set any group. It just works. Issue can be closed.

**Comment by matthewpalmer** [comment]
Awesome. Thanks for following up—I'm sure it will help someone in the future!
