### ISSUE TITLE
LocksmithError Code=3 "The operation couldn’t be completed. 

### ISSUE THREAD

**Issue by focusedonfit** [matthewpalmer/Locksmith#42]
Hello,

I'm using the 2.0 branch and I'm receiving this error:

Error Domain=Focused_on_Training.LocksmithError Code=3 "The operation couldn’t be completed. 

```
do {
        try Locksmith.saveData(["password": "\(pwd)"], forUserAccount: "\(currentUser.username)", inService: "FocusedOnTraining")
        
    } catch let error as NSError {
        print("\(error)")
    }
```

Thanks for your assistance.

**Comment by matthewpalmer** [comment]
Hmm not sure sorry. Does it work if you hard-code some strings in for `pwd` and `currentUser.username`? What are the types of these values? In particular, you might get strange results if they are optionals.

**Comment by focusedonfit** [comment]
They are strings, I have tried hardcoding some strings and receive the same result. Does code 3 mean anything?

**Comment by matthewpalmer** [comment]
What OS/device/SDK version?

**Comment by matthewpalmer** [comment]
Also if possible could you please attach a sample project that shows the issue? :)

**Comment by focusedonfit** [comment]
I didn't realize that there is an .updateData method. I'm saving the data after the user signs in. Hitting this after deleting/installing during testing. Keychain entry already exists the second time! Closing.. Thank you!

**Comment by adrianmacneil** [comment]
I got stuck on this too. Would be helpful if you could add a quick note to the readme explaining the difference between updateData and saveData :smile:

**Comment by matthewpalmer** [comment]
@adrianmacneil great idea! Just added this, but let me know if you think the issue could be expressed more clearly (I wasn't super happy with what I came up with). Thanks for the suggestion! :)
