### ISSUE TITLE
WatchKit 2.0 support

### ISSUE THREAD

**Issue by Naethyn** [matthewpalmer/Locksmith#47]
WatchKit 2.0 can store and retrieve data in the keychain and it would be useful if Locksmith could be used in the watch extension.

**Comment by matthewpalmer** [comment]
Hmm that’s definitely an interesting idea. Do you know what it would take to bring Locksmith up to speed for that?

(I’m really sorry it took me so long to reply!)

**Comment by matthewpalmer** [comment]
Sorry, accidentally closed

**Comment by taiheng** [comment]
I'm interested in helping with this. I've got the project modified so carthage will build both frameworks, as well as the podspec file. Still in the process of updating the example project to demonstrate that it works.

**Comment by taiheng** [comment]
Added OSX and watchOS to podspec and created a Locksmith_wOS shared framework target for carthage.
Added examples for iOS and wOS.
tucali/locksmith@e2d600f3c7d08c305067695682befbac5eee2980

**Comment by matthewpalmer** [comment]
Added a watch target in 2.0.1, but couldn't quite get a watch example together. Fairly sure it should work with WatchKit 2.0, but please let me know if not :)

**Comment by matthewpalmer** [comment]
@taiheng awesome—thanks very much! A watch example would be awesome if you could possibly introduce it into master now (I cleaned up project structure a bit in the latest release)

**Comment by taiheng** [comment]
The watch example is fairly basic in the pull request right now, adding watch connectivity to the example will be next. Otherwise the project does compile for watch and phone.
