### ISSUE TITLE
wipe all locksmith data?

### ISSUE THREAD

**Issue by longbowww** [matthewpalmer/Locksmith#51]
Is there any "wipe all" command?

**Comment by matthewpalmer** [comment]
Yep, there's a `clearKeychain` class func on Locksmith. I should add this to the docs though :)

**Comment by ObjColumnist** [comment]
Hi @matthewpalmer, is this available in the latest version?

**Comment by longbowww** [comment]
@ObjColumnist in my app i only support 1 logged in user/saved user credentials at a time, so i worked around it using `try! Locksmith.deleteDataForUserAccount("myAPP")`
