### ISSUE TITLE
Support Xcode 7 beta 6 via Carthage

### ISSUE THREAD

**Issue by prefect42** [matthewpalmer/Locksmith#53]
Crashes at runtime

dyld: lazy symbol binding failed: Symbol not found: __TFSs24withUnsafeMutablePointeru0_rFTRq_FGVSs20UnsafeMutablePointerq__q0__q0_
  Referenced from: /Users/mdellagi/Library/Developer/CoreSimulator/Devices/5EEB8704-4DA7-4D43-B767-658CDD7C2E33/data/Containers/Bundle/Application/C589F01D-F6DB-4CB1-A69D-A28AA8013FE1/meinmd.app/Frameworks/Locksmith.framework/Locksmith
  Expected in: /Users/mdellagi/Library/Developer/CoreSimulator/Devices/5EEB8704-4DA7-4D43-B767-658CDD7C2E33/data/Containers/Bundle/Application/C589F01D-F6DB-4CB1-A69D-A28AA8013FE1/meinmd.app/Frameworks/libswiftCore.dylib

dyld: Symbol not found: __TFSs24withUnsafeMutablePointeru0_rFTRq_FGVSs20UnsafeMutablePointerq__q0__q0_
  Referenced from: /Users/mdellagi/Library/Developer/CoreSimulator/Devices/5EEB8704-4DA7-4D43-B767-658CDD7C2E33/data/Containers/Bundle/Application/C589F01D-F6DB-4CB1-A69D-A28AA8013FE1/meinmd.app/Frameworks/Locksmith.framework/Locksmith
  Expected in: /Users/mdellagi/Library/Developer/CoreSimulator/Devices/5EEB8704-4DA7-4D43-B767-658CDD7C2E33/data/Containers/Bundle/Application/C589F01D-F6DB-4CB1-A69D-A28AA8013FE1/meinmd.app/Frameworks/libswiftCore.dylib

```
switch type {
        case .Create:
            status = withUnsafeMutablePointer(&result) { SecItemAdd(requestReference, UnsafeMutablePointer($0)) }
        case .Read:
            status = withUnsafeMutablePointer(&result) { SecItemCopyMatching(requestReference, UnsafeMutablePointer($0)) }
        case .Delete:
            status = SecItemDelete(requestReference)
        case .Update:
            status =  Locksmith.performUpdate(requestReference, result: &result)
}
```

**Comment by matthewpalmer** [comment]
Woah that's pretty terrifying! What's the version of iOS/Swift/Locksmith you're using? When was the most recent `pod install`/`pod update`? (FYI introduced some breaking API changes to master yesterday, so if you need 1.2 support check out the `1.2.2` branch :) .)

**Comment by prefect42** [comment]
I am using the latest commit in the 2.0 branch. The one from my pull request, really ;-)
I fixed it in my fork by dropping just working with the pointer directly…
Not sure if that is a bad thing or not.

case .Create:
            status = SecItemAdd(requestReference, &result)
case .Read:
            status = SecItemCopyMatching(requestReference, &result)

fixes it.

**Comment by matthewpalmer** [comment]
Ah okay. Master is now on Swift 2/iOS 9, so it's the recommended way of using Locksmith. The 2.0 branch is obsolete and will probably be deleted soon.
I wonder if this is an issue in master as well now though... doesn’t seem to be from the tests, but you can never be certain with stuff like this.

I think I'm going to close this, but feel free to reopen if you think it's an issue in `master` and I'll definitely look into it more. Thanks very much for your help 😀

**Comment by prefect42** [comment]
master does not compile at all when using carthage. 

The following build commands failed:
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler

**Comment by prefect42** [comment]
Would be good if you could provide a working branch for Xcode 7 Beta 6 and Carthage.

**Comment by matthewpalmer** [comment]
Agreed. I think this is my fault for not testing that it'd all work ok. Will have to look into this more for sure. I assume the output of `xcode-select -p` is the correct Xcode beta?

**Comment by prefect42** [comment]
Yes its the correct beta. `/Applications/Xcode-beta.app/Contents/Developer`
I only have Xcode 7 Beta 6 installed on my machine.

Your 2.0 does compile fine.
The only problem is, it crashes at run time.

My fork at frnde/Locksmith is working and I do not really see the necessity for the UnsafeMutablePointer stuff in your switch. After removing it and working directly with the pointer everything is working as expected.

**Comment by prefect42** [comment]
Sent you a pull request

**Comment by jcjee** [comment]
I am not able to compile using Xcode 7 Beta 6 with Carthage too, and I have the same "CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler" error. Thanks and hope you can fix this soon!

**Comment by matthewpalmer** [comment]
I believe this has been fixed in #55, but let me know if not :)

**Comment by prefect42** [comment]
Yep.

**Comment by prefect42** [comment]
master is working fine here now
