### ISSUE TITLE
iOS 9.0 only?

### ISSUE THREAD

**Issue by ivasic** [matthewpalmer/Locksmith#56]
Is there a specific reason why Locksmith is iOS 9 and above?
Seems to be working fine in iOS 8.0, also your project deployment target is set to iOS 8, only in Podspecs you've limited it to 9+.

**Comment by matthewpalmer** [comment]
Don't think so—will drop the requirement soon :)

**Comment by matthewpalmer** [comment]
Updated in ef4a62f475b478c5d993da6e3b844. Thanks for letting me know! 👍
