### ISSUE TITLE
OSX Support

### ISSUE THREAD

**Issue by nickoneill** [matthewpalmer/Locksmith#58]
Assuming the UIKit dependency gets resolved, this should work as-is with OSX as well. Maybe some `@availability` stuff to prevent usage of anything iOS or OSX-specific on the alternate platform.

**Comment by matthewpalmer** [comment]
Interesting idea. Will look into it over the weekend! 😀

**Comment by matthewpalmer** [comment]
Just added in 2.0.1! Thanks for the suggestion :). Please reopen or open a new issue if it doesn't work.
