### ISSUE TITLE
Sometimes Can't Load from Keychain

### ISSUE THREAD

**Issue by jonallured** [matthewpalmer/Locksmith#6]
I've got another weird one, but first - I've got [a commit](https://github.com/jonallured/Locksmith/commit/affc67d622693f270b7697b86bed3b65e5d40e83) that adds some stuff to show the logging in the app. I wasn't sure if you'd want it, so I didn't do a PR, but let me know if you'd like me to do that.

Anyway, I've got four devices I'm testing with:
- iPhone 6
- iPhone 5S
- iPhone 5
- iPad 4

When I run the Locksmith app in the simulator or build it directly to these devices everything works perfectly. Then, when I archive the app and distribute it though HockeyApp, things get weird.

The iPad and 5 also work normally, but then on both the 6 and 5S, loading doesn't work. I tap save, then I tap load and get nothing.

I've got the iOS Console app up and I'm not seeing anything there and the `performRequest` method isn't returning an error, so I don't know what's going on.

This is what was happening to me with the code I wrote myself and is why I got interested in Locksmith in the first place. I'm new to iOS development, so I assumed I was doing something wrong, but now I'm seeing this behavior with the Locksmith code too, so I thought I'd open an issue on it.

One thing that I'm wondering about is how TouchID could possibly play into this. One of the hardware differences between the devices that are behaving and those that aren't is that TouchID sensor - maybe that matters?

I don't know, seems like a longshot. Have you been able to get this app to work on a device where you haven't just built it directly from Xcode? I don't know if you use HockeyApp or TestFlight or something else, but I'd be very interested to know if it's working for you.

Thanks!
Jon

**Comment by kukabi** [comment]
Hi @matthewpalmer, I got the same issue on Xcode 6.1.1 (6A2008a) and lost some hours, there doesn't seem to be a note on the master branch README, it'd be good to have it there...thanks!

**Comment by matthewpalmer** [comment]
@kukabi the note was removed from the readme because this issue was fixed in later versions of this library and Xcode. Sorry about you losing so much time though! Please let me know if this continues to be an issue if you update Xcode to 6.2.
