### ISSUE TITLE
Can't build a project after installing Locksmith through CocoaPods.

### ISSUE THREAD

**Issue by andrew8712** [matthewpalmer/Locksmith#62]
Xcode Version 7.0 beta 6 shows at least 2 issues in Locksmith.framework:
<img width="1421" alt="screen shot 2015-09-10 at 2 55 43 pm" src="https://cloud.githubusercontent.com/assets/2883524/9784274/ada544fc-57c3-11e5-9d5d-9bee40a0cf1f.png">
I use Swift 2.0 and use use_frameworks! flag in Pods file.

**Comment by andrew8712** [comment]
I just forked the repo and can see that you've fixed those issues already, but pod is outdated. When you'll have a chance to update it?

**Comment by katunch** [comment]
Same error here. Xcode 7 (7A218) GM
Please update the podspec to the latest HEAD

**Comment by katunch** [comment]
Ok it turned out that Locksmith 1.2.2 will be installed if you defined the `platform :ios, '8.0'`.
If you put `pod 'Locksmith', '~> 2.0'` in your pod file and run `pod install` the following error occurs: 
```
[!] Unable to satisfy the following requirements:

- `Locksmith (~> 2.0)` required by `Podfile`
```

**Comment by matthewpalmer** [comment]
Ah so I think the current pod spec requires iOS 9. I'm in the process of dropping this to iOS 8 though :)

**Comment by matthewpalmer** [comment]
Updated the pod to 2.0.1, so hopefully this will be fixed :). Let me know if not though.

**Comment by fabdarice** [comment]
pod 'Locksmith', '~> 2.0.1' doesn't fix it.
I still got a lot of errors when trying to build the app

**Comment by matthewpalmer** [comment]
@fabdarice ah, that's frustrating. What errors are you seeing?

I just created a new project in Xcode with the following podfile and it seemed to work for me

```
platform :ios, '8.0'
use_frameworks!
target 'MyProject' do
  pod 'Locksmith', '~> 2.0.1'
end
```

**Comment by fabdarice** [comment]
There's 195 compilations errors.

platform :ios, '8.0'
use_frameworks!
pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'master'

pod 'SwiftyJSON', '~> 2.2.1'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'
pod 'KeychainAccess'
pod 'Locksmith', '~> 2.0.1'

<img width="1137" alt="screen shot 2015-09-13 at 12 25 52 pm" src="https://cloud.githubusercontent.com/assets/2358008/9838438/9cfd5044-5a12-11e5-967d-fa9f41223ce1.png">

**Comment by matthewpalmer** [comment]
What version of Xcode is this? Can you please upload a sample project with the issue—I'm having trouble replicating it on my machine. 

Thanks very much :)
