### ISSUE TITLE
Feedback and an alternative approach

### ISSUE THREAD

**Issue by rvangraan** [matthewpalmer/Locksmith#65]
Hi there,

I've been working on another aspect of the IOS Keychain for a few months and had to face much the same craziness as I think you had to do. I saw your commits using Protocol Extensions last week and started thinking about how to use it. Our project doesn't really need passwords stored in the Keychain, but do need Certificates, Identities and Key Pairs. The sad thing is that the Apple APIs become much crazier for these 3 classes. My goal was to end up with three classes that represent actual items in the Keychain (not items that still need to be added or generated or updates to existing items). I struggled with the correct abstractions for the Apple `kSecAttrXYZ` mappings to Swift properties too. So after many, many hours of fighting Swift and Generics and OpenSSL, I came up with this:
https://github.com/curoo/IOSKeychain/pull/3
This is not done and things will change. There are lots to cleanup and I want to get rid of Keychain.swift. Eventually all the actual code will be encapsulated by `KeychainItem` and derivatives. You might be interested in this: https://github.com/curoo/IOSKeychain/pull/3/files#diff-aa5b9813fc9f149c0b877e44a5bd0ced

Which is my take on using Protocols for dealing with the attributes. Essentially I wrapped the groups of attributes into a protocol and then injected them directly into the concrete class:
```
public protocol KeychainCommonClassProperties : KeyChainAttributeStorage {
    var itemAccessGroup: String? { get}
    var itemLabel: String? { get }
}

extension KeychainCommonClassProperties where Self : KeychainCommonClassProperties {
    public var itemLabel: String? {
        get { return attributes[String(kSecAttrLabel)] as? String }
    }
    public var itemAccessGroup: String? {
        get { return attributes[String(kSecAttrAccessGroup)] as? String }
    }
}
```
I also decided against your approach of building up the separate dictionaries for the queries/future updates as you did here:
https://github.com/matthewpalmer/Locksmith/blob/master/Source/Locksmith.swift#L104

My approach was to split the problem into two domains. The first deals with existing Keychain objects (and they derive from `KeychainItem`) and then the objects that you send to the `SecItemXYZ` APIs derive from 'KeychainDescriptor'. Both derive from a common class that has a SecurityClass and an attribute dictionary that stores the IOS Keychain Attributes in the format you need to send or receive from the IOS APIs. This means I don't current need setters on `KeychainItem` properties, but if I were to implement something that has to be updatable, I will add another type of Descriptor object that holds the new attribute values. (I.e. setting an itemLabel on an existing key or password item will modify the attributes on a `UpdateDescriptor` object that I will send to the `SecItemUpdate`

I don't yet plan to implement the `KeychainPassword` yet, which will overlap with what you've done, but it is pretty straightforward.

I am much happier with this approach than I was with any of my many, many previous attempts at encapsulating this crazy API. Hope there is something useful for you to use. 

Rudolph

**Comment by matthewpalmer** [comment]
Thanks so much for sharing your thoughts and approach! I really like the way you've done things, and this is an awesome write up of it (you should do a blog post!). This will definitely be helpful for when I get around to implementing certificates, identities, etc. 

Going to close this because there aren't any actionable items, but I really appreciate you taking the time to share your approach in detail—it will definitely be helpful going forward :)
