### ISSUE TITLE
Ability to retrieve persistent references to items.

### ISSUE THREAD

**Issue by mspasov** [matthewpalmer/Locksmith#66]
It'll be great to have the ability to retrieve persistent reference to items. I'm using this with the network extension to configure VPN profiles.

**Comment by matthewpalmer** [comment]
Hmm that's a really interesting idea. How would you expect to be able to interact with that? Ie what sort of API would you want for creating/reading/etc?

**Comment by matthewpalmer** [comment]
Closing, feel free to reopen if this remains an issue :)
