### ISSUE TITLE
Getting unresolved identifier "Locksmith" after updateing to xcode 7 

### ISSUE THREAD

**Issue by felixdkatt** [matthewpalmer/Locksmith#68]
Use of unresolved identifier 'Locksmith'

i removed the files and re-did my pod install but still getting the issue

**Comment by matthewpalmer** [comment]
Hmm interesting. Could you possibly add a sample project that shows the issue? I can't seem to reproduce it :/

**Comment by felixdkatt** [comment]
Not an issue it. It was a cocoa pods issue. I had a lot of issues when upgrading to xcode 7 due to cocoapods. Mainly library and header path issues.
