### ISSUE TITLE
Crash in readFromSecureStore(): EXC_BREAKPOINT (code=1, subcode=0x1009544dc)

### ISSUE THREAD

**Issue by albertbori** [matthewpalmer/Locksmith#69]
```
public extension ReadableSecureStorable where Self : GenericPasswordSecureStorable {
    func readFromSecureStore() -> GenericPasswordSecureStorableResultType? {
        do {
            let result = try performSecureStorageAction(performReadRequestClosure, secureStoragePropertyDictionary: asReadableSecureStoragePropertyDictionary)
            return GenericPasswordResult(resultDictionary: result!)
        } catch {
            print(error)
            return nil
        }
    }
}
```

It looks like `result!` is nil when trying to use it as a constructor for `GenericPasswordResult(resultDictionary:)`. Not sure why it'd be nil, but we should probably log it instead of allowing it to crash?

I got this running the app on my iPhone 6, tethered to my mac, deployed from Xcode. Optimization settings for my main app are off, but are on for Locksmith.

**Comment by ObjColumnist** [comment]
Experiencing the same issue.

Doing an if let on the result has fixed the crash for me, but I am unsure if it is the appropriate solution e.g. should this check be done in performSecureStorageAction instead.

**Comment by pheld** [comment]
+1 on the issue and temporary solution.

**Comment by matthewpalmer** [comment]
Thanks for letting me know! Merged in the fix from the PR, but please reopen if the issue occurs again :)
