### ISSUE TITLE
Read data from keychain using protocols after app killed from memory

### ISSUE THREAD

**Issue by levibostian** [matthewpalmer/Locksmith#72]
I have been using Locksmith for a few months now with great luck, library is wonderful and has worked great so far!

I am upgrading apps to Swift 2.0, so upgrading this library is part of this process. I upgraded the code into my apps project and read the README to get an idea of how the API has changed. 

I used to use the methods: `LockSmith.saveData()`, `LockSmith.loadDataForUserAccount()`, etc. but now I see you added support for protocols...

---

So I was looking through [the docs](https://github.com/matthewpalmer/Locksmith#power-to-the-protocols) for protocols and saw this code:
```
let account = TwitterAccount(username: "_matthewpalmer", password: "my_password")
try account.createInSecureStore()
```
and I am able to read the data I need with:
```
let result = account.readFromSecureStore()
result.username // => "_matthewpalmer"
result.password // => "my_password"
```

Looks great. Now, what I am having issues with, what if I create an instance of my TwitterAccount struct, save it to keychain, then I kill the app from memory? The variable `account` that is required in order to read the data from keychain will be cleared and no longer available for me to use. Then I just cannot create a new TwitterAccount struct because it requires me knowing "username" and "password" but I am not going to force my user to give me this data every time the app is launched. 

In previous versions of LockSmith, "service name" was used in order to read data for my specific app. I see this is gone, so how am I able to read my TwitterAccount `username` and `password` after the app has been killed and removed from memory such as powering down the user device?

**Comment by matthewpalmer** [comment]
Thanks so much for using Locksmith!

`username` and `password` aren't required by the `GenericPasswordSecureStorable`—the requirement is for `account` and `service`. So the equivalent of `Locksmith.loadDataForUserAccount("myUserAccount")` might be something like

```swift
struct Account: ReadableSecureStorable {
  let account = "myUserAccount"
  let service = "myService" // this might be your bundle identifier
}

let data = Account().readFromSecureStore()
```

And for creating you can make `data` anything that you could normally put into the equivalent `saveData` method, like a username and password :)

Also—and this is not required to make the above work properly—you could save the username in NSUserDefaults and read it back later (I would strongly discourage saving the password there though).

Let me know if any of that doesn't make sense or doesn't work—I didn't actually try out any of the examples I gave :)

**Comment by levibostian** [comment]
:+1: thank you! That helped.

**Comment by tylerbobella** [comment]
@matthewpalmer and @levibostian Sorry to reopen this but I am having the same issue and do not full understand the solution. Would I need to have two structs then? `TwitterAccount` for setting the `username` and `password` then have a struct `Account` for accessing the information in `TwitterAccount` once the app has been closed? Let me know if my question is too vague.

**Comment by levibostian** [comment]
@tylerbobella, from the example that @matthewpalmer gave in his answer, you do not need to have the username and password available in order to create a TwitterAccount object. You need the username and bundle identifier of your app (which both of these can be safely accessible in your app via NSUserDefaults as this info is public information). So you would use the username of the logged in user and the bundle identifier to create a new TwitterAccount object, read it from the keystore and then pull the password out. 

The issue that I was having and the reason that I asked the original question in this issue is because I thought that you needed the username and the password in order to create a TwitterAccount object and read from the keystore. This is incorrect. It is actually the username and bundle identifier (if you originally set it up and saved this way. @matthewpalmer's example used username and bundle identifier and I think that is a great idea so I chose that as well). 

Make any sense at all? (it has been a while. I am trying to refresh my memory on this issue to help you out).

**Comment by matthewpalmer** [comment]
@levibostian I think you're totally right—thanks!

@tylerbobella we also have an issue #92 that might be tracking something similar to the problem you're having/the question you're asking? Feel free to have a read through that thread and drop any concerns in there :)

Cheers guys :+1:

**Comment by tylerbobella** [comment]
@levibostian sorry for the late reply! Ahhh! I see now. So assuming the above, 

`struct Account: ReadableSecureStorable {
  let account = "myUserAccount"
  let service = "myService" // this might be your bundle identifier
  let password: String
    var data: [String: AnyObject] {
        return ["password": password]
}`

from @matthewpalmer example I can now set `data` by `Account(password: "password)`. But how would I look up this specific account I guess is where I get confused. Sorry if this is more of a stackoverflow question, if so I can post a question there. 

Thanks again for speedy replies I really appreciate it!

**Comment by levibostian** [comment]
```swift
struct TwitterAccount: ReadableSecureStorable, 
                       CreateableSecureStorable,
                       DeleteableSecureStorable,
                       GenericPasswordSecureStorable {
  let username: String
  let password: String

  let service = "myService" // this might be your bundle identifier (recommend to keep your keychain unique)
  var account: String { return username }
  var data: [String: AnyObject] {
    return ["password": password]
  }
}

let account = TwitterAccount(username: "_matthewpalmer", password: "my_password")
try account.createInSecureStore() // saves TwitterAccount to keychain on our device.

let userDefaults = NSUserDefaults.standardUserDefaults()
userDefaults.setValue(username, forKey: "twitter_username")
userDefaults.synchronize()
```
The example above is taken from the README (and then I added the NSUserDefaults part). We simply want to create an object that stores our username and password. I use NSUserDefaults to store our username to retrieve later on. The username is not sensitive data so it is not a security risk to put it in there. 

There are fields in our TwitterAccount object that are optional. We do not need them:  

* `username`
* `password`

We use them because well, we want to save a username and password for our Twitter user logged in. We could change `username` and `password` to really any variables that we want representing the data that we want to save. For example, I usually store the `access_token` for OAuth2 along with the `username` so I don't use the `password` field. It is flexible to store whatever you need. 

Now, there are fields that are required for our object in order to be created, saved, read later on:  

* `service`
* `account` 
* `data`

`service` and `account` are required for the `GenericPasswordSecureStorable` protocol (which we want to use to store a password). In our case here, we are being simple and making the account variable be our username. 

`data` is required for the `CreateableSecureStorable` protocol. To keep it simple, we are returning the password field. We could return anything but password is the important data we want to save to keychain. We could add more fields here if we wanted to. 

---

Ok so now getting to your question @tylerbobella. 
The code example above created a `TwitterAccount` and saved it to the device. Now comes to what you want to know and what I was asking originally. What happens when the device is restarted, the app is closed, etc. How do we read the password in this situation? 

```swift
let userDefaults = NSUserDefaults.standardUserDefaults()
let twitterUsername = userDefaults.valueForKey("twitter_username") 

let dictionary = Locksmith.loadDataForUserAccount(twitterUsername)
let password = dictionary["password"]
```
There is your Twitter password saved earlier.
