### ISSUE TITLE
Catch error for readFromSecureStore?

### ISSUE THREAD

**Issue by quicklywilliam** [matthewpalmer/Locksmith#75]
This is a silly question, but how do we catch and/or use an error generated from readFromSecureStore?

**Comment by sealz** [comment]
```
do {
  try record.readFromSecureStore()
} catch _ {
  print("Something went wrong")
}
```

Replace the `catch _` with `catch <SomeErrorType>` to be more specific, but I have no idea what error types are thrown.

**Comment by matthewpalmer** [comment]
Thanks @sealz!
