### ISSUE TITLE
What does the error 'Duplicate' mean?

### ISSUE THREAD

**Issue by kwerle** [matthewpalmer/Locksmith#78]
I can dig, but I'd love for the docs to be clearer.

**Comment by matthewpalmer** [comment]
Thanks for the feedback :) Added convenient links back to the docs in the README to help out with this

**Comment by davisford** [comment]
For anyone else who gets here wondering what `duplicate` error means...Apple's docs are horrible, and the link in the PR to change the `README` lands on a generic page now (i.e. link broken).  

[Here's a good explanation of what it means](https://useyourloaf.com/blog/keychain-duplicate-item-when-adding-password/)

If the link is broken for future, in a nutshell, you need to pass the `inService` (can be a static identifier) with the `forUserAccount`.

Wasted too much time on this.
