### ISSUE TITLE
Creating a custom "sortable" extension in a different file than locksmith.swift

### ISSUE THREAD

**Issue by matt-walker** [matthewpalmer/Locksmith#79]
Hello,

I am looking to create my own "CustomSortable" extension, similar to "InternetPasswordSecureStorable"  that builds upon other previously defined "Sortable" extensions. This seems only possible right now if I put the extension declaration in the same file as LockSmith.swift. This is because some of the extension members are private, i.e. "private var accountSecureStoragePropertyDictionary", and extensions can only access private members of their extending type when defined in the same file. It would be great to be able to write the custom sortable extension in a different file so I don't need to touch this plugin. Is it possible to make the extension members non-private or maybe am I missing something in general? Appreciate any help.

**Comment by matthewpalmer** [comment]
Hmm I'm not sure I'm comfortable making those properties non-private. In this case, I think your best bet is to fork Locksmith and make the required changes.

Sorry it took me so long to get back to you!
