### ISSUE TITLE
Question about the read implementation

### ISSUE THREAD

**Issue by raulriera** [matthewpalmer/Locksmith#84]
Hi there,

I was going throng the library and came across this
```swift
// ReadableSecureStorable lets us read the account from the keychain
let result = account.readFromSecureStore()
```
Is this really the desired functionality? Why would I want to read from the keychain when I already have the object? Maybe I am missing something important here

**Comment by raulriera** [comment]
Yeah never mind, I was mixing 2 things, I should just "save data" when I want to store something specific and only use the `GenericPasswordSecureStorable` with actual account information. I was trying to mix this into an OAuthToken system

**Comment by lukeredpath** [comment]
I'm afraid I'm as baffled as you about how reading is supposed to work. Why go to all the effort of wrapping up your credentials in an object only to throw that all away when you read from the keychain.

**Comment by amarcadet** [comment]
+1
Really need some explanation here too.

**Comment by matthewpalmer** [comment]
I think the example in the readme strives for simplicity at the expense of explicitness (which is probably a bad thing… would love to see a PR to improve the docs on this!)

A quick example (certainly not great code or anything) that might clear things up

```swift
// Let's say that Twitter accounts can be in one of two states: they can be unauthenticated (`MaybeATwitterAccount`) and authenticated (`TwitterAccount`).
// The latter has functionality that the former does not, like tweeting.

struct MaybeATwitterAccount: GenericPasswordSecureStorable, CreateableSecureStorable {
    let username: String
    let password: String
    
    let service = "Twitter"
    let account = "Twitter user"
    
    var data: [String: AnyObject] { return ["password": password] }
    
    func isValid() -> Bool { return true }
}

struct TwitterAccount: GenericPasswordSecureStorable, ReadableSecureStorable {
    let service = "Twitter"
    let account = "Twitter user"
    let username: String
}

// Maybe we get Twitter account credentials via a form in our app
let prospective = MaybeATwitterAccount(username: "_matthewpalmer", password: "my_password")
if prospective.isValid() { // Maybe we do some validation against the server
    try! prospective.createInSecureStore() // We know the account's ok, so we save it
}

// Some time later in our app
let lastUsername = "_matthewpalmer" // maybe we get this from user defaults (or even from the keychain)
let proper = TwitterAccount(username: lastUsername)

// Now we can get the password from the keychain (we probably wouldn't do this out here, it might be done inside a more useful method on the TwitterAccount itself, like a function called `tweet()` or something.
let password = proper.readFromSecureStore()!.data!["password"] as! String
```

**Comment by matthewpalmer** [comment]
I did notice in coming up with this example that it would have been slightly easier to cook up if the `data` requirement on `CreateableSecureStorable` wasn't a computed property but rather a function (or maybe even an argument to the `createInSecureStore` function). Let me know if that's an API change that would suit you better and I can roll it out in the next larger release.
