### ISSUE TITLE
Conforming to CreateableSecureStorable protocol

### ISSUE THREAD

**Issue by chrismanderson** [matthewpalmer/Locksmith#85]
Trying out your library, running into an issue where I'm conforming to the `CreateableSecureStorable` protocol, but I'm being requred to implement the `createInSecureStore` method. I don't see anything information on having to implement that method in the docs, nor what an implementation would look like. What am I missing?

      struct Test : CreateableSecureStorable {
        let name: String
        
        var data: [String: AnyObject] {
          return [
            "name" : name
          ]
        }
      }

   gives  `Protocol requires function 'createInSecureStore()' with type '() throws -> ()' (Locksmith.CreateableSecureStorable)`

**Comment by matthewpalmer** [comment]
Hi Chris

I think you might need to conform to `GenericPasswordSecureStorable` or `InternetPasswordSecureStorable`—those protocols should give you the functionality for `createInSecureStore` :)

Thanks
Matt

**Comment by waltermvp** [comment]
@matthewpalmer so to conform to `CreateableSecureStorable` we need to conform to the other protocols? 
Or will an empty implementation of the required functions work as well?
