### ISSUE TITLE
password for account and service example?

### ISSUE THREAD

**Issue by rlaferla** [matthewpalmer/Locksmith#95]
Given an account and service, how do I retrieve the password?  Also, set password for account + service.

It would be good to see this in the Quickstart examples...

**Comment by matthewpalmer** [comment]
Using the class method based API you can set a service with the third parameter to each method, `inService`. If omitted, Locksmith will use a default value.

I'm not sure that I agree that it should be in the quick start. If there's significant demand I can add it, but for now I'm going to leave as is.

**Comment by rlaferla** [comment]
I still can't get this to work.  I'm looking for a drop-in Swift replacement for SSKeychain:

```
[SSKeychain passwordForService:@“MyApp” account:anAccount.username];

[SSKeychain setPassword:anAccount.password forService:@"MyApp" account:anAccount.username];
```

What's the equivalent code for Locksmith?
