### ISSUE TITLE
tvOS release

### ISSUE THREAD

**Issue by raulriera** [matthewpalmer/Locksmith#98]
Any plans to make a release with tvOS?

**Comment by crashoverride777** [comment]
This should already work in tvOS.

**Comment by raulriera** [comment]
Yes, but the code is not released yet..

**Comment by crashoverride777** [comment]
Fair enough. 
I meant that the basic saving data methods etc should already work in your own project if you just copy the .swift file into your project and add it to your tvOS target.

**Comment by matthewpalmer** [comment]
Thought I'd made a release with tvOS, but I might have forgotten. Will make a new one tonight 👍

**Comment by matthewpalmer** [comment]
2.0.5 should work now, but let me know if not and I'll investigate :)
